spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shopee-clone-db:3306/shopee-db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: 6jZy59I3gNLH1Pj45sJT9/E0SSQUA1yNcAV1yZaXiwE
      expiration: 86400000 # 1 day

stripe:
  api:
    key: sk_test_51PchJnKrNg4CjtgGgbUYj56kZ2rKeWpFUnmUEPTLtJofgGDavpJO9t0RrLeNSUeNPWa5VmNWrdJOsbobNr4dyw1c00HSTVxG2m