package com.practice.fullstackbackendspringboot.utils;

public class StringUtil {

    public static final String PHOTO_DIRECTORY = System.getProperty("user.home") + "/Downloads/uploads/";
    public static final String X_REQUESTED_WITH = "X-Requested-With";
    public static final String ACCOUNT_EXISTS = "ACCOUNT ALREADY EXISTS!";
    public static final String DELETED = "PRODUCT DELETED!";
    public static final String INVALID_CREDENTIALS = "INVALID CREDENTIALS!";
    public static final String USER_NOT_FOUND = "USER NOT FOUND: ";
    public static final String LOGIN_SUCCESSFUL = "LOGIN SUCCESSFUL!";
    public static final String OUT_OF_STOCK = "PRODUCT IS OUT OF STOCK!";
    public static final String WRONG_PASSWORD = "WRONG PASSWORD!";
    public static final String PASSWORD_NOT_MATCH = "PASSWORD DOES NOT MATCH!";
    public static final String CASH_ON_DELIVERY = "Cash on Delivery";
    public static final String ADMIN_CREATED = "ADMIN USER CREATED SUCCESSFULLY!";
    public static final String ADMIN_ALREADY_EXISTS = "ADMIN USER ALREADY EXISTS!";
    public static final String PENDING = "PENDING";
    public static final String ORDER_CANCELLED = "CANCELLED";
    public static final String ORDER_IS_CANCELLED = "The order has been cancelled";
    public static final String ORDER_COMPLETED = "COMPLETED";
    public static final String RATED = "RATED";
    public static final String ORDER_DELIVERED = "Parcel has been delivered";
    public static final String ORDER_CANCELLED_OR_NOT_ACTIVE = "ORDER IS CANCELLED OR NOT ACTIVE";
    public static final String TO_PAY = "TO PAY";
    public static final String TO_SHIP = "TO SHIP";
    public static final String TO_RECEIVE = "TO RECEIVE";
    public static final String ORDER_NOT_FOUND = "ORDER NOT FOUND";
    public static final String PREPARE_ORDER = "Seller is preparing your order(s)";
    public static final String ORDER_CONFIRMATION = "Order Confirmation";
    public static final String SHIPPING_ORDER = "Seller is preparing to ship your order(s)";
    public static final String OUT_FOR_DELIVERY ="Parcel is out for delivery";
    public static final String PRODUCT_NOT_FOUND = "PRODUCT NOT FOUND ";
    public static final String PRODUCT_ALREADY_EXISTS = "PRODUCT ALREADY EXISTS!";
    public static final String CATEGORY_NOT_FOUND = "CATEGORY NOT FOUND";
    public static final String STORE_NOT_FOUND = "STORE NOT FOUND: ";
    public static final String RATING_EXCEEDS_LIMIT = "Invalid rating: Rating must be between 1 and 5";
    public static final String Created_Date = "createdDate";
    public static final String Product_Sold = "productSold";
    public static final String Low_Product_Sold = "lowProductSold";
    public static final String Product_Name = "productName";
    public static final String Color = "colors";
    public static final String Replied = "replied";
    public static final String True = "true";
    public static final String False = "false";
    public static final String Rating = "rating";
    public static final String Listed = "listed";
    public static final String Suspended = "suspended";
    public static final String Role = "role";
    public static final String User = "user";
    public static final String Seller = "seller";
    public static final String Admin = "admin";
    public static final String Online = "online";
    public static final String Frozen ="frozen";
    public static final String ACCESS_DENIED = "Access denied: You do not have sufficient permissions to perform this action";
    public static final String LAST_MODIFIED = "lastModified";
    public static final String StripePayment = "Stripe Payment";
    public static final String Stripe = "stripe";
    public static final String Cash = "cash_on_delivery";
    public static final String Shopee= "Shopee";
    public static final String Php = "php";
    public static final String SuccessUrl = "http://localhost:5173/user/purchase/order/to-ship";
    public static final String CancelUrl = "http://localhost:5173/checkout";
    public static final String StoreNameExists = "Store name already exists: ";
    public static final String INVALID_TRANSACTION = "Sellers cannot purchase their own products";

}
